// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "missile":return img`
....................
....................
....................
....................
....................
.......e............
.......ee...........
....444b7777777777..
..44455ee7777777772.
...4444b7777777777..
.......ee...........
.......e............
....................
....................
....................
....................
`;
            case "image2":
            case "Fighter_plane":return img`
...................................
...................................
...................................
...................................
...................................
...................................
...............fff.................
...............fbbfff..............
......ccc.....ffbbbbff.............
......fbcc...ffbbbbbbf.............
......fbbcc..fcccccccff............
......fbbbc.ccbbbbbbbccc...........
......fbbbccbbbbbbbbbbb9c..........
......cfbbbbbbbbbbbbbb999c.........
.....cbbcbbbbbbbbbb11199bbc........
....fbbcccccccbbbb99111bbbbcc......
....fffffccbbcccbbbbbbbbbbbbbcc....
.....fbbbbbbbbbcccbbbbbbbbbbbbcf...
.....fbbbbbbbbbbbccbbbbbbbbbbbbbf..
....fbbbbbbbbbbbbbffffffffffffff...
....ffffffffbbbbbbff...............
............ffffff.................
...................................
...................................
...................................
...................................
`;
            case "image3":
            case "Bullets":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . 5 5 5 . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 5 5 5 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "Enemy_missile":return img`
...................................
...................................
...................................
...................................
...................................
.............d.....................
............dd......ccc............
...........ddd......ccc............
....bbbbbf1bbbbbbbbbbbbee..........
..2bbbbbb1fbbbbbbbbbbbbee4444......
.22bbbbbbf1bbbbbbbbbbbbee544444....
.22bbbbbb1fdddbbbbbbcccee5544444...
.22bbbbbbf1bbbbbbbbbbbbee544444....
..2bbbbbb1fbbbbbbbbbbbbee44444.....
....bbbbbf1bbbbbbbbbbbbee..........
...........ddd......ccc............
............dd.....................
.............d.....................
...................................
...................................
...................................
...................................
...................................
...................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
